import type { Metadata } from 'next';
import { Montserrat, Milonga } from 'next/font/google';

import './globals.css';
import Header from '@/components/layout/header';
import Footer from '@/components/layout/footer';
import { Providers } from './Providers';

export const milonga = Milonga({ subsets: ['latin'], weight: ['400'] });
const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Tokunbo',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased`}>
        <Providers>
          <section className="grid min-h-screen grid-rows-[auto_1fr_auto]">
            <Header />
            {children}
            <Footer />
          </section>
        </Providers>
      </body>
    </html>
  );
}
